// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCBgHHgFd7Iu5vlWjLe6O7dyH3c1ijrU',
    appId: '1:1058031343797:web:275703980741aaea0706fc',
    messagingSenderId: '1058031343797',
    projectId: 'giftardo-43381',
    authDomain: 'giftardo-43381.firebaseapp.com',
    storageBucket: 'giftardo-43381.firebasestorage.app',
    measurementId: 'G-D5EFP7L0JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DsEeyyaVMwVaSGcc5LvVj7J63u0v_us',
    appId: '1:1058031343797:android:fb4c3a2bc1c22e320706fc',
    messagingSenderId: '1058031343797',
    projectId: 'giftardo-43381',
    storageBucket: 'giftardo-43381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8NrRs7iWdIBQq9tePmxhLIIvspFdf_0',
    appId: '1:1058031343797:ios:eabdf7a2cf1c565c0706fc',
    messagingSenderId: '1058031343797',
    projectId: 'giftardo-43381',
    storageBucket: 'giftardo-43381.firebasestorage.app',
    iosBundleId: 'com.example.giftardo',
  );
}
